# Market Data Pipeline Configuration
symbols:
  # Major Tech Stocks
  - AAPL   # Apple Inc.
  - GOOGL  # Alphabet Inc.
  - MSFT   # Microsoft Corporation
  - AMZN   # Amazon.com Inc.
  - TSLA   # Tesla Inc.
  
  # Financial Sector
  - JPM    # JPMorgan Chase & Co.
  - BAC    # Bank of America Corp
  - GS     # Goldman Sachs Group Inc.
  
  # Market Indices
  - SPY    # SPDR S&P 500 ETF
  - QQQ    # Invesco QQQ Trust
  - IWM    # iShares Russell 2000 ETF

# Data settings
data_settings:
  period: "1y"           # Data period (1d, 5d, 1mo, 3mo, 6mo, 1y, 2y, 5y, 10y, ytd, max)
  interval: "1d"         # Data interval (1m, 2m, 5m, 15m, 30m, 60m, 90m, 1h, 1d, 5d, 1wk, 1mo, 3mo)
  
# Alert settings
alerts:
  price_change_threshold: 5.0  # Alert if daily price change > 5%
  volume_multiplier: 2.0       # Alert if volume > 2x average volume
  
# Paths
paths:
  data_dir: "data"
  reports_dir: "reports" 
  logs_dir: "logs"
